/** @file
 *  @author zhouminghui
 *  2018.12.5
 *  intl 英文词库
 */

const en_US = {
    'aelf.': ' ',
    'aelf.WalletDetail': 'WalletDetail',
    'aelf.TransactionList': 'Transaction List',
    'aelf.AddressBook': 'Address Book',
    'aelf.SystemSetting': 'System Setting',
    'aelf.HelpCenter': 'Help Center',
    'aelf.About': 'About ELF Official Wallet',
    'aelf.Contact': 'Contact',
    'aelf.Copy Address': 'Copy Address',
    'aelf.Create Wallet': 'Create Wallet',
    'aelf.Create Keypair': 'Create Keypair',
    'aelf.Import Keypair': 'Import Keypair',
    'aelf.Clear Wallet': 'Clear Wallet',
    'aelf.Unlock Wallet': 'Unlock Wallet',
    'aelf.Keypair Name': 'Keypair Name',
    'aelf.Extend Management': 'Extend Management',
    'aelf.Key Pairs': 'Key Pairs',
    'aelf.Application Management': 'Application Management',
    'aelf.Receive': 'Receive',
    'aelf.Home': 'Home',
    'aelf.Permissions': 'Permissions',
    'aelf.Lock': 'Lock',
    'aelf.Clear': 'Clear',
    'aelf.Settings': 'Settings',
    'aelf.Create': 'Create',
    'aelf.CreateWallet': 'Create Wallet',
    'aelf.CreateWallets': 'Create Wallet',
    'aelf.ImprotWallets': 'Import Wallet',
    'aelf.Becareful01': 'Password is used to encrypt private keys and mnemonic'
    + ' words. At least 9 bits are mixed uppercase and numeric.',
    'aelf.Becareful02': 'AElf wallet will not store the password, nor can it help you find it. Please bear in mind!',
    'aelf.WalletName': 'Wallet Name',
    'aelf.Password': 'Password',
    'aelf.At least 9 bits': 'At least 9 bits',
    'aelf.Not Enough': 'Not Enough',
    'aelf.Strong': 'Strong',
    'aelf.Confirm Password': 'Confirm Password',
    'aelf.Agree': 'Agree',
    'aelf.Refuse': 'Refuse',
    'aelf.Service and Privacy Policy': 'Service and Privacy Policy',
    'aelf.Backup Wallet': 'Backup Wallet',
    'aelf.AElf Wallet': 'AELF Wallet',
    'aelf.Manage your wallet addresses': 'Manage your wallet addresses',
    'aelf.Becareful03': 'Please backup your Mnemonic in a secure environment!',
    'aelf.Becareful04': 'No secure Mnemonic backup means no secure wallet.',
    'aelf.Becareful05': 'In the case of wallet or App deletion,',
    'aelf.Becareful06': 'you will need your Mnemonic to recover your wallet.',
    'aelf.Mnemonic': 'Mnemonic',
    'aelf.Private Key': 'Private Key',
    'aelf.Next': 'Next',
    'aelf.Submit': 'Submit',
    'aelf.Backup Mnemonic': 'Backup Mnemonic',
    'aelf.Becareful07': 'Mnemonic is used to restore your wallet or reset your password,',
    'aelf.Becareful08': 'Please write them down carefully and keep them in a secure location！',
    'aelf.Becareful09': 'Please DO NOT use screen capture!',
    'aelf.Becareful010': 'If anyone obtains your Mnemonic, they WILL obtain your digital assets!',
    'aelf.Confirm Mnemonic ': 'Confirm Mnemonic',
    'aelf.ConfirmMnemonic': 'Confirm Mnemonic',
    'aelf.hint01': 'Mnemonic is not in the right sequence, please rearrange!',
    'aelf.hint02': 'To confirm your backup, please click on the Mnemonic in order.',
    'aelf.Copy Private Key': 'Copy Private Key',
    'aelf.Copy': 'Copy',
    'aelf.Close': 'Close',
    'aelf.Delete Wallet': 'Delete Wallet',
    'aelf.Wallet Name': 'Wallet Name',
    'aelf.Backup': 'Backup',
    'aelf.Change Password': 'Change Password',
    'aelf.Transaction List': 'Transaction List',
    'aelf.Contact': 'Contact',
    'aelf.Commit': 'Commit',
    'aelf.New contacts': 'New contacts',
    'aelf.Name': 'Name',
    'aelf.Payee wallet address': 'Payee wallet address',
    'aelf.Old password': 'Old password',
    'aelf.Forget your password': 'Forget your password? Importing mnemonic or private key can be reset.',
    'aelf.Immediately import': 'Immediately import',
    'aelf.hint03': 'In this wallet, there is no Mnemonic when import Private Key. But we can get '
    + 'Private Key when we import Mnemonic.',
    'aelf.Import': 'Import',
    'aelf.System Setting': 'System Setting',
    'aelf.Network': 'Network',
    'aelf.NetworkCon01': 'Current Wallet Service URL',
    'aelf.NetworkCon02': 'What did the service provider do?',
    'aelf.NetworkCon03': '1.Broadcast your transaction when you transfer tokens to others.',
    'aelf.NetworkCon04': '2.Provide information when you open the page which shows transaction detail.',
    'aelf.NetworkCon05': 'How to change the service provider?',
    'aelf.NetworkCon06': '1.Click the URL.',
    'aelf.NetworkCon07': '2.Then, you can change it.',
    'aelf.NetworkCon08': 'Default provider is',
    'aelf.Language': 'Language',
    'aelf.Help Center': 'Help Center',
    'aelf.HelpTitle01': 'What is a mnemonic?',
    'aelf.HelpTitle02': 'What is a keystore?',
    'aelf.HelpTitle03': 'What are public key and private key?',
    'aelf.HelpTitle04': 'What is the AElf Wallet?',
    'aelf.HelpTitle05': 'How to change the password?',
    'aelf.HelpTitle06': 'What if I forget my password?',
    'aelf.mnemonicCon01': 'The Mnemonics is equivalent to the bank card + '
    + 'password of a traditional financial institution. '
    + 'Please keep it in a safe place. A Mnemonics is another manifestation of a plaintext private'
    + ' key that is designed to help users remember'
    + ' complex private keys (64-bit hashes). Mnemonicss are generally composed of 12, 15, 18, and 21 words. These'
    + ' words are taken from a fixed vocabulary. The order of generation '
    + 'is also based on a certain algorithm. The Mnemonics is an unencrypted private '
    + 'key. When people get your Mnemonics, you can take away your assets with little effort.',
    'aelf.mnemonicCon02': 'Therefore, users must pay attention to three points when backing up the Mnemonics:',
    'aelf.mnemonicCon03': '1. Use physical media as much as possible. For example, write Mnemonicss on paper. '
    + 'Do not use screenshots or photos on networked devices as much as possible to prevent hackers from stealing.',
    'aelf.mnemonicCon04': '2. Verify that the backup Mnemonics is correct multiple times.'
    + ' Once you have misread a letter or word, it will bring great suffering to the sub'
    + 'sequent retrieval of the correct Mnemonics.',
    'aelf.mnemonicCon05': '3. Keep the Mnemonics after the backup in a safe place, and do a good job of anti-theft and anti-lost measures.',
    'aefl.keystoreCon01': 'The Keystore file is a file format (JSON) for storing the private key. It uses user-defined password encryption to protect the wallet to a certain extent, and the degree of protection depends on the password strength of the wallet. If the password is similar to 123456, it is extremely unsafe.',
    'aefl.keystoreCon02': 'So users must pay attention to three points when backing up Keystore:',
    'aefl.keystoreCon03': '1. use encrypted Keystore files that are not commonly used and as complex as possible.',
    'aefl.keystoreCon04': "2. Be sure to remember the password to encrypt Keystore. Once you forget the password, you lose the right to use Keystore, and aelf can't help you retrieve the password. So please keep it safe.",
    'aefl.keystoreCon05': 'Keystore Demo:',
    'aelf.publickeyCon01': 'The control of funds in a wallet depends on the ownership and control of the private key.',
    'aelf.publickeyCon02': 'In block-chain transactions, the private key is used to generate the signature necessary for the payment currency to prove the ownership of the fund. Private keys must always be kept confidential, because once they are disclosed to a third party, assets protected by the private key are also compromised.',
    'aelf.publickeyCon03': "It is different from keystore, which is a private key file after encryption. As long as the password strength is strong enough, even hackers attack, it is very difficult to decipher. The private key is not actually stored in the network, but is generated and stored by the user in a file or a simple database, called a wallet. The user's wallet address is generated by the private key through the elliptic curve encryption to generate the public key, and then generate the 36-bit address.",
    'aelf.publickeyCon04': 'The style of the private key is a 64 bit 16 binary hash value string.',
    'aelf.walletCon01': 'AElf Wallet is a new digital money wallet, providing users with safer, more efficient and convenient services.',
    'aelf.walletCon02': 'AElf Wallet supports AElf intelligent contract digital currency.',
    'aelf.walletCon03': 'At present, BTC and ETH are not supported at the moment, but we are in support of the AElf standard token.',
    'aelf.changepasswordCon01': 'Passwords can be modified at the wallet management interface.',
    'aelf.forgetpasswordCon01': "In the decentralized wallet, all users'user authentication content, such as transaction password, private key, mnemonic and so on, are stored locally in the user's mobile phone, not in the centralized server, so if the user forgets the password, it is impossible to reset the password through a third-party team.",
    'aelf.forgetpasswordCon02': 'The only solution is to set up new passwords by re importing mnemonic or private keys.',
    'aelf.About AElf Official Wallet': 'About AElf Official Wallet',
    'aelf.Use Agreement': 'Use Agreement',
    'aelf.Privacy Policy': 'Privacy Policy',
    'aelf.changelanguage': 'Language change',
    'aelf.languageSelect': 'Select',
    'aelf.Transaction Record': 'Transaction Record',
    'aelf.Receive': 'Receive',
    'aelf.Send': 'Send',
    'aelf.Copy URL': 'Copy URL',
    'aelf.Transaction Details': 'Transaction Details',
    'aelf.To Address': 'To Address',
    'aelf.Transaction': 'Transaction',
    'aelf.Amount to send': 'Value / Amount to Send',
    'aelf.Balance': 'Balance',
    'aelf.New Provider': 'New Provider',
    'aelf.slow': 'Slow',
    'aelf.fast': 'Fast',
    'aelf.Modaltips': 'Password error, you have',
    'aelf.Modaltimes': 'more chances',
    'aelf.Back Home': 'Back Home',
    'aelf.error page': 'error page',
    'aelf.cannot connect chain': 'cannot connect chain',
    'aelf.PleaseBackUp': 'NOTE! Please Back Up!',
    'aelf.BackUpCon01': 'Aelf reminds you again that the blockchain wallet is different from the traditional website account, which is a cryptographic-based decentralized account system.',
    'aelf.BackUpCon02': "You must save the wallet's private key and transaction password, and any accidents will result in the loss of assets.",
    'aelf.BackUpCon03': 'Aelf prompts you to make a backup, conduct a small transaction test, and start the journey of use.',
    'aelf.BackUpCon04': 'Backup your wallet recovery phrase is extremely important when your wallet is lost or forgotten.',
    'aelf.Backup now': 'Backup now',
    'aelf.The passwords confirmed error.': 'The passwords confirmed error.',
    'aelf.The passwords is not strong.': 'The passwords is not strong.',
    'aelf.Extension Management': 'Extension Management',
    'aelf.Backup NightELF': 'Backup NightELF',
    'aelf.Delete NightELF': 'Delete NightELF',
    'aelf.Timer Locks': 'Timer Locks',
    'aelf.Load From Backup': 'Load From Backup',
    'aelf.Please select the file': 'Please select the file',
    'aelf.Click here': 'Click here',
    'aelf.Timing Lock Settings': 'Timing Lock Settings',
    'aelf.Application': 'Application',
    'aelf.Login': 'Login',
    'aelf.Details': 'Details',
    'aelf.Submit Backup': 'Submit Backup',
    'aelf.Manage': 'Manage',
    'aelf.Delete': 'Delete',
    'aelf.Copy Address': 'Copy Address',
    'aelf.Please select the timing lock-in time:': 'Please select the timing lock-in time:',
    'aelf.Application details': 'Application details'
};

export default en_US;
