/** @file
 *  @author zhouminghui
 *  2018.12.5
 *  intl 中文词库
 */

// 中文词典
const zh_CN = {
    'aelf.': ' ',
    'aelf.WalletDetail': '钱包详情',
    'aelf.TransactionList': '交易记录',
    'aelf.AddressBook': '联系人',
    'aelf.SystemSetting': '系统设置',
    'aelf.HelpCenter': '帮助中心',
    'aelf.About': '关于 ELF 官方钱包',
    'aelf.Contact': '联系人',
    'aelf.Copy Address': '复制钱包地址',
    'aelf.Create Wallet': '创建钱包',
    'aelf.Create Keypair': '创建密钥',
    'aelf.Import Keypair': '导入密钥',
    'aelf.Clear Wallet': '删除钱包',
    'aelf.Unlock Wallet': '解锁钱包',
    'aelf.Keypair Name': '密钥对别名',
    'aelf.Extend Management': '扩展管理',
    'aelf.Key Pairs': '密钥对',
    'aelf.Application Management': '应用管理',
    'aelf.Receive': '钱包地址',
    'aelf.Home': '首页',
    'aelf.Permissions': '权限',
    'aelf.Lock': '锁定',
    'aelf.Clear': '删除',
    'aelf.Settings': '设置',
    'aelf.Create': '创建钱包',
    'aelf.CreateWallet': '新建钱包',
    'aelf.CreateWallets': '新建钱包',
    'aelf.ImprotWallets': '导入钱包',
    'aelf.Becareful01': '密码用于加密私钥和助记词, 至少9位混合大小写和数字。',
    'aelf.Becareful02': 'AElf钱包不会储存密码，也无法帮您找回，请务必牢记！',
    'aelf.WalletName': '钱包名称',
    'aelf.Password': '密码',
    'aelf.At least 9 bits': '密码长度至少9位',
    'aelf.Not Enough': '不够安全',
    'aelf.Strong': '安全',
    'aelf.Confirm Password': '确认密码',
    'aelf.Agree': '同意',
    'aelf.Refuse': '拒绝',
    'aelf.Service and Privacy Policy': '服务与政策',
    'aelf.Backup Wallet': '备份钱包',
    'aelf.AElf Wallet': 'AELF 钱包',
    'aelf.Manage your wallet addresses': '管理您的钱包地址',
    'aelf.Becareful03': '请在安全的环境下备份助记词！',
    'aelf.Becareful04': '没有妥善备份就无法保障资产安全；',
    'aelf.Becareful05': '删除程序或钱包后，',
    'aelf.Becareful06': '您需要通过备份的助记词来会恢复钱包！',
    'aelf.Mnemonic': '助记词',
    'aelf.Private Key': '私钥',
    'aelf.Next': '下一步',
    'aelf.Submit': '提交',
    'aelf.Backup Mnemonic': '备份助记词',
    'aelf.Becareful07': '助记词用于恢复钱包或者重置钱包密码，',
    'aelf.Becareful08': '仔细抄写下助记词并放在安全的地方！',
    'aelf.Becareful09': '请勿截图!',
    'aelf.Becareful010': '如果有他人获取你的助记词，他将直接获取你的资产。',
    'aelf.ConfirmMnemonic': '确认助记词',
    'aelf.hint01': '顺序不对，请校对！',
    'aelf.hint02': '请按顺序点击助记词，以确认您正确备份。',
    'aelf.Copy Private Key': '复制私钥',
    'aelf.Copy': '复制',
    'aelf.Close': '关闭',
    'aelf.Delete Wallet': '删除钱包',
    'aelf.Wallet Name': '修改钱包名称',
    'aelf.Backup': '备份',
    'aelf.Change Password': '修改密码',
    'aelf.Transaction List': '交易记录',
    'aelf.Contact': '联系人',
    'aelf.Commit': '提交',
    'aelf.New contacts': '新建联系人',
    'aelf.Name': '姓名',
    'aelf.Payee wallet address': '钱包地址',
    'aelf.Old password': '旧密码',
    'aelf.Forget your password': '忘记密码？导入助记符或私钥可以重置。',
    'aelf.Immediately import': '立即导入',
    'aelf.hint03': '在这个钱包中，导入私钥时没有助记词。但是，当我们导入助记词时，我们可以得到私钥。',
    'aelf.Import': '导入',
    'aelf.System Setting': '系统设置',
    'aelf.Network': '网络',
    'aelf.NetworkCon01': '当前钱包服务的URL',
    'aelf.NetworkCon02': '该服务做了什么？',
    'aelf.NetworkCon03': '1、在将Token转让给他人时，广播您的交易。',
    'aelf.NetworkCon04': '2、在打开显示交易细节的页面时提供信息。',
    'aelf.NetworkCon05': '如何变更服务？',
    'aelf.NetworkCon06': '1、点击上方 URL.',
    'aelf.NetworkCon07': '2、然后，你可以更改它。',
    'aelf.NetworkCon08': '默认提供的为:',
    'aelf.Language': '语言',
    'aelf.Help Center': '帮助中心',
    'aelf.HelpTitle01': '什么是助记词？',
    'aelf.HelpTitle02': '什么是keystore？',
    'aelf.HelpTitle03': '什么是公钥私钥？',
    'aelf.HelpTitle04': 'AElf钱包介绍',
    'aelf.HelpTitle05': '如何修改密码？',
    'aelf.HelpTitle06': '如果我忘记密码了怎么办？',
    'aelf.mnemonicCon01': '助记词相当于传统金融机构的银行卡+密码。请把它放在安全的地方。助记词是明文私钥的另一种表现形式，它被设计成帮助用户记住复杂的私钥（64位散列）。'
    + '记忆法一般由12, 15, 18个单词和21个单词组成。这些词是从固定的词汇中提取出来的。生成顺序也是基于一定的算法。助记词是一个未加密的私钥。任何人得到你的助记词后，就可以不费吹灰之力夺走你的资产。',
    'aelf.mnemonicCon02': '因此，用户在备份助记符时必须注意三点：',
    'aelf.mnemonicCon03': '1、尽可能采用物理介质，例如把助记词写在纸上，尽可能不要采用截屏或者拍照之后放在联网设备上，以防被黑客窃取。',
    'aelf.mnemonicCon04': '2、多次验证备份的助记词是否正确，一旦抄错一个字母或单词，那么将对后续找回正确的助记词带来巨大苦难。',
    'aelf.mnemonicCon05': '3、将备份后的助记词妥善保管，做好防盗防丢措施。',
    'aelf.keystoreCon01': 'Keystore 文件是存储私钥的一种文件格式（JSON）。它使用用户自定义密码加密，以起到一定程度的保护作用，而保护的程度取决于用'
    + '户加密该钱包的密码强度，如果类似于123456这样的密码，是极为不安全的。',
    'aelf.keystoreCon02': '所以用户在备份助记词时一定要注意三点：',
    'aelf.keystoreCon03': '1、使用不常用，并且尽可能复杂的密码加密Keystore文件。',
    'aelf.keystoreCon04': '2、一定要记住加密Keystore的密码，一旦忘记密码，那么你就失去了Keystore的使用权，并且aelf无法帮你找回密码。所以请妥善保管。',
    'aelf.keystoreCon05': 'Keystore密码样式：',
    'aelf.publickeyCon01': '钱包中资金的控制取决于相应私钥的所有权和控制权。',
    'aelf.publickeyCon02': '在区块链交易中，私钥用于生成支付货币所必须的签名，以证明资金的所有权。私钥必须始终保持机密，因为一旦泄露给第三方，相当于该私钥保护下的资产也拱手相让了。',
    'aelf.publickeyCon03': '它不同于keystore，keystore是加密过后的私钥文件，只要密码强度足够强，即使黑客攻击，破译难度也很高。私'
    + '钥实际上并不是存储在网络中，而是由用户生成并储存在一个文件或者简单的数据库中，称为钱包。用户的钱包地址就是由私钥通过椭圆曲线加密生成公钥，进而生成以0x开头的42位地址。',
    'aelf.publickeyCon04': '私钥的样式为64位16进制哈希值字符串。',
    'aelf.walletCon01': 'AElf钱包是一款全新的数字货币钱包，为用户提供更安全、高效、便捷的服务。',
    'aelf.walletCon02': 'AElf钱包支持AElf智能合约数字货币。',
    'aelf.walletCon03': '目前暂不支持BTC和ETH，但是符合AElf标准的代币我们都支持。',
    'aelf.changepasswordCon01': '密码可以在钱包管理界面上修改。',
    'aelf.forgetpasswordCon01': '在去中心化钱包中，所有用户的用户身份验证内容，如交易密码、私钥、助记词等都保存在用户手机本地，并不是'
    + '保存在中心化服务器中，所以用户如果忘记密码是没有办法通过第三方团队来重置密码的。',
    'aelf.forgetpasswordCon02': '唯一的解决办法是通过重新导入助记词或者私钥来设置新的密码。',
    'aelf.About AElf Official Wallet': '关于 AELF 钱包',
    'aelf.Use Agreement': '使用协议',
    'aelf.Privacy Policy': '隐私政策',
    'aelf.changelanguage': '选择语言',
    'aelf.languageSelect': '请选择',
    'aelf.Transaction Record': '交易记录',
    'aelf.Send': '发送',
    'aelf.Receive': '接收',
    'aelf.Copy URL': '复制链接',
    'aelf.Transaction Details': '交易细节',
    'aelf.To Address': '发送地址',
    'aelf.Transaction': '交易',
    'aelf.Amount to send': '发送值/价值',
    'aelf.Balance': '等量',
    'aelf.New Provider': '新供应商',
    'aelf.slow': '慢',
    'aelf.fast': '快',
    'aelf.Modaltips': '密码错误，您还有',
    'aelf.Modaltimes': '次机会',
    'aelf.Back Home': '返回',
    'aelf.error page': '错误页',
    'aelf.cannot connect chain': '无法连接到链',
    'aelf.PleaseBackUp': '注意!请立即备份钱包!',
    'aelf.BackUpCon01': 'aelf在此提示您，区块链钱包不同于传统网站账户，它是基于密码学的去中心化账户系统。',
    'aelf.BackUpCon02': '你必须保存好钱包和私钥和交易密码，任何意外发生将导致资产丢失。',
    'aelf.BackUpCon03': 'aelf提示您做好备份，在进行小额交易测试后，再开启使用之旅。',
    'aelf.BackUpCon04': '备份助记词在您丢失钱包或忘记密码时，能帮助您恢复钱包。',
    'aelf.Backup now': '立即备份助记词',
    'aelf.The passwords confirmed error.': '两次输入不一致',
    'aelf.The passwords is not strong.': '密码强度不够',
    'aelf.Extension Management': '管理',
    'aelf.Backup NightELF': '备份 NightELF',
    'aelf.Delete NightELF': '删除 NightELF',
    'aelf.Timer Locks': '定时锁定',
    'aelf.Load From Backup': '导入加密备份',
    'aelf.Please select the file': '请选择备份文件',
    'aelf.Click here': '点击这里',
    'aelf.Timing Lock Settings': '定时锁定设置',
    'aelf.Application': '应用',
    'aelf.Login': '登录',
    'aelf.Details': '查看详情',
    'aelf.Submit Backup': '提交备份',
    'aelf.Manage': '管理',
    'aelf.Delete': '删除',
    'aelf.Copy Address': '复制地址',
    'aelf.Please select the timing lock-in time:': '请选择定时锁定时间:',
    'aelf.Application details': '应用详情',
    'aelf.Cancel': '取消',
    'aelf.Authorization details': '授权详情',
    'aelf.Authorized domain name:': '授权域名:',
    'aelf.Contract Address:': '合约地址:',
    'aelf.Contract Name:': '合约名称:',
    'aelf.Description:': '合约介绍:',
    'aelf.Enable Whitelist': '启用白名单',
    'aelf.Delete All': '删除全部权限',
    'aelf.Whitelist': '白名单',
    'aelf.New Contract Method': '新增合约权限',
    'aelf.Delete Contract Method': '删除合约权限',
    'aelf.Details of contract changes': '合约变更详情'
};

export default zh_CN;
